# Generated by Django 5.0.7 on 2024-09-22 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_date_of_birth_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.product')),
            ],
            options={
                'unique_together': {('employee', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='ListOfProduct',
        ),
    ]
