# Generated by Django 4.2.7 on 2024-12-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quantity_salesentry_inventoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fromages', 'Fromages'), ('Sauces', 'Sauces'), ('Poisson', 'Poisson'), ('Poulet', 'Poulet'), ('Divers', 'Divers')], default='Divers', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(choices=[('Top Chef', 'Top Chef'), ('Ali', 'Ali'), ('Adnane', 'Adnane'), ('Yozi Food', 'Yozi Food'), ('Divers', 'Divers')], default='Divers', max_length=20),
        ),
    ]
