# Generated by Django 4.2.7 on 2025-04-08 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_salesrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProductDayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('voiture', models.IntegerField(default=0)),
                ('sortie', models.IntegerField(default=0)),
                ('retour', models.IntegerField(default=0)),
                ('vendu', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.seller')),
            ],
            options={
                'unique_together': {('seller', 'product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySellerStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('voiture', models.IntegerField(default=0)),
                ('sortie', models.IntegerField(default=0)),
                ('retour', models.IntegerField(default=0)),
                ('vendu', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.seller')),
            ],
            options={
                'unique_together': {('seller', 'product', 'date')},
            },
        ),
    ]
