# Generated by Django 4.2.7 on 2025-04-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sellerproductdayentry_dailysellerstockrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='critical_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
