# Generated by Django 4.2.7 on 2025-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
