# Generated by Django 4.2.7 on 2025-04-19 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_seller_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('carburant', 'Carburant'), ('salaire', 'Salaire'), ('achat_stock', 'Achat Stock'), ('frais_livraison', 'Frais Livraison'), ('divers', 'Divers')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='expenses/')),
            ],
        ),
    ]
