# Generated by Django 4.2.7 on 2025-04-19 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Vente', 'Vente'), ('Investissement', 'Investissement'), ('Aide', 'Aide'), ('Divers', 'Divers')], default='Divers', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
