# Generated by Django 4.2.7 on 2025-04-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_inventoryloadrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
