# Generated by Django 4.2.7 on 2025-04-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_cashflowentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('method', models.CharField(choices=[('cheque', 'Chèque'), ('virement', 'Virement'), ('espece', 'Espèces'), ('autre', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'À venir'), ('paid', 'Réglé')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
